version: '3'
services:
  master:
    container_name: master
    image: redis:7.0
    ports:
      - 6379:6379
  replica-1:
    container_name: replica-1
    image: redis:7.0
    ports:
      - 6380:6379
    command: redis-server --slaveof master 6379
  replica-2:
    container_name: replica-2
    image: redis:7.0
    ports:
      - 6381:6379
    command: redis-server --slaveof master 6379
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=master:master,replica-1:replica-1,replica-2:replica-2
    ports:
      - "8081:8081"
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3307:3306 # HOST:CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: admin
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - C:/test/mysql/data:/var/lib/mysql