server:
  port: 8088

logging:
  config: classpath:logback-spring.xml

spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/testdb?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: jwttest
    password: dkssud123#
    hikari:
      maximum-pool-size: 40
      max-lifetime: 42000
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

jwt:
  token:
    access:
      expiration: 86400000    # 24시간
    refresh:
      expiration: 604800000   # 7일
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK

redis:
  master:
    host: localhost
    port: 6379
  replicas:
    - host: localhost
      port: 6380
    - host: localhost
      port: 6381